### ISSUE TITLE
Ctrl + Shift + N shortcut is taken

### ISSUE THREAD

**Issue by tariibaba** [Cside/chrome-notion-search#35]
Please change the default key to open the popup to something other than <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>N</kbd>, as this keyboard shortcut is already used to open a new incognito window in Chrome and other popular browsers, which is something users do pretty frequently.

I recommend the <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> keyboard shortcut:
- "Open the search **P**opup"?
- <kbd>P</kbd> being on the right side of keyboards with the highly used QWERTY layout will make it easier to press this keyboard shortcut, as typically the <kbd>Ctrl</kbd> and <kbd>Shift</kbd> keys pressed will be the ones on the left side of the keyboard.
- <kbd>Ctrl</kbd> + <kbd>P</kbd> is already used in the Notion web app to open the built-in popup. This could make the shortcut easier to remember.
- The default <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> opens a native OS print dialog instead of the browser-specific one. This is not a frequently performed action.

**Comment by Cside** [comment]
Thank you for your suggestion. I will respond within a day.

**Comment by tariibaba** [comment]
Okay

**Comment by Cside** [comment]
Your suggestion is very good, so I will change the default key to `Ctrl + Shift + P` as you suggested.
I'd like to prepare a notice for existing users as well, so I think it will take about a week at the latest until to release it.
Until release, please change the key from `chrome://extensions/shortcuts` .

**Comment by Cside** [comment]
I've released this feature as v2.0.0. Thank you for your good suggestion.
If any problems happen for 5 days, this issue will be closed.
