### ISSUE TITLE
Search can be more responsive

### ISSUE THREAD

**Issue by tariibaba** [Cside/chrome-notion-search#82]
Hey there! I think it would be great to add a spinner to the search box while the search is happening, which would increase the responsiveness and user experience of the app.

To do this, I suggest displaying a spinner at the same spot as the search icon, just like in the Notion web app search box:
![gif](https://user-images.githubusercontent.com/73142389/220411770-c7b20bf9-e906-4985-8648-929a275d60f1.gif)

This will allow users to quickly identify when the search is in progress, even if they don't know the exact time remaining.

I believe this simple modification will make the app more user-friendly. What do you think about this idea?

We could easily create a [spinner](https://flowbite.com/docs/components/spinner/#progress-spinner) using a [Tailwind](https://tailwindcss.com/) component library like [Flowbite](https://flowbite.com/).
Or we could examine the CSS code used for the spinner in the Notion web app and apply it to our own spinner implementation.

**Comment by Cside** [comment]
Hello.
To be honest, I didn't even realise that the Notion web app had a spinner until you told me about it, and it doesn't seem that useful to me at the moment. (This is just my opinion. It does not negate your opinion)
So at the moment I am not positive about adding this feature, but my opinion may change in the future.
Thank you for your suggestion.
